# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e29f753f2bc1baa91407657d3939269a1fa2e4d11da6c262c1ebb27a55259c73444301d7f23318e7b169aac298aeefad39fa31499640b9797388b622675b6d5

test:
  secret_key_base: ef98fc03c4a1609fcf15dbdfb77838017f217b81152bbd444b1c4d2b3fb13b0409ec34c52ffdfa16c78d60bf419fd74dfefc48a1920a2a3e867398fc7b940b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
